fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"

# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    puppet: "https://github.com/abstractitptyltd/abstractit-puppet.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    apache:
      repo:  "https://github.com/puppetlabs/puppetlabs-apache.git"
      ref:  "1.4.1"
    puppetserver_gem: "https://github.com/puppetlabs/puppetlabs-puppetserver_gem.git"
    puppetdb: "https://github.com/puppetlabs/puppetlabs-puppetdb.git"
    postgresql: "https://github.com/puppetlabs/puppetlabs-postgresql.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"

  symlinks:
    profile_puppetmaster: "#{source_dir}"
